spring:

  web:
    error:
      include-message: always
      include-path: always
      include-stacktrace: always
      include-binding-errors: always
      include-exception: true

custom:
  jwt:
    secret: chiaveAbbastanzaLungaDaCodificareUnTokenJwtPEROINTEST
    expiration: 360000