spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DbProva
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: test

  graphql:
    graphiql:
      enabled: true